KS-1-5  finally
xiokrius/KotlinSprint pull request #5
Opened 2024-01-30 21:52 UTC by xiokrius

2024-01-30 21:54 UTC, xiokrius commented
Сделал через String.format вывод даты и времени

2024-01-31 09:02 UTC, ievetrovdev requested changes

2024-01-31 09:02 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    val secondsInSpace = 6360
Количество секунд которое Гагарин провел в космосе, нужно было взять из прошлой задачи - 6480

2024-01-31 09:02 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    val minutes: Int = remainingSecondsAfterHours / 60
Чтобы снизить риск ошибок, предлагаю еще вынести 60 в константу. Кроме того это тоже
 [магическое число](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что не является хорошей практикой.

2024-01-31 09:02 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    val remainingSecondsAfterHours: Int = secondsInSpace % 3600
3600 это [магическое число](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), оно не дано в задаче, следовательно должно получиться путем вычисления

2024-01-31 09:02 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +
По поводу форматирования: пустые строки между объявленными переменными не нужны. Для красоты кода и лучшей читабельности можно отделить пустой строкой переменную или блок переменных с расчетами.

2024-01-31 09:08 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +
Нейминги я бы привел в более общепринятый вид. Ты указал префикс проекта, номера урока и задачи, тут все хорошо, а в названии лучше указать сделал то-то. Это относится и к названию пулл реквеста, и к названию ветки.

2024-01-31 09:09 UTC, ievetrovdev requested changes

2024-01-31 09:09 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    val formattedTime = String.format("%02d:%02d:%02d", hours, minutes, seconds)
С выводом все корректно)

2024-02-05 18:25 UTC, merged